[settings]
always_keep_install = false
always_keep_download = false

plugin_autoupdate_last_check_duration = "0"
idiomatic_version_file_enable_tools = ["go", "node", "ruby"]

verbose = false
http_timeout = "30s"
jobs = 2
raw = false

not_found_auto_install = true
paranoid = false

experimental = false

# configure messages displayed when entering directories with config files
status = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }

[settings.task]
output = "prefix"

[tools]
go = "1.26"
golangci-lint = "latest"

kubectl = "1.34"
kind = "latest"
k9s = "latest"

oras = "1"
cosign = "3"
syft = "1"

usage = "latest"
yq = "latest"
pre-commit = "latest"
